#!/bin/bash
MONGO_PORT="27017"

#Restore function, downloads the selected file from S3Bucket, unzips, restores and clean up files.
function getIp {
  read -a IP <<<$(dig mongo | grep mongo. | awk '{print $5}' | tail -n 3 | xargs )
  echo "Found mongodb hosts: ${IP[*]}"
}

function checkHostSlave {
  for CANDIDATE in ${IP[*]}
  do
    IS_MASTER=$(mongo --host $CANDIDATE --eval "printjson(db.isMaster())" | grep 'ismaster')
    if [[ $IS_MASTER == *"false"* ]]; then
     MONGO_HOST=$CANDIDATE
     echo "$MONGO_HOST detected as slave"
    fi
  done
}
getIp
checkHostSlave

echo 

echo "Starting backup..."

DATE=$(date +$DATEFORMAT)
FILENAME=$FILEPREFIX$DATE.tar.gz
FILE=/backup/backup-$FILENAME

mongodump --quiet -h $MONGO_HOST -p $MONGO_PORT $DB_ARG
tar -zcvf $FILE dump/
aws s3api put-object --bucket $S3BUCKET --key $FILENAME --body $FILE
echo "Cleaning up..."
rm -rf dump/$FILE
